#!/bin/sh

maxSizeImg='10000000' 
# maxSizeImg=10mb
# install glow bat chafa

image() {
	sizeFile=$(stat -c %s "$1")
	if [ $sizeFile -lt $maxSizeImg ]; then
		chafa "$1" -f sixel -s "$(($2-2))x$(($3-2))" | sed 's/#/\n#/g'
	else
		echo "Very large file: $sizeFile"
	fi
}

batorcat() {
	file="$1"
	shift
	if command -v bat > /dev/null 2>&1
	then
		bat --color=always --style=plain --pager=never "$file" "$@"
	else
		cat "$file"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
	*.tgz|*.tar.gz) tar tzf "$1" ;;
	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
	*.tar.txz|*.txz) xz --list "$1" ;;
	*.tar) tar tf "$1" ;;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
	*.rar) unrar l "$1" ;;
	*.7z) 7z l "$1" ;;
	*.[1-8]) man "$1" | col -b ;;
	*.iso) iso-info --no-header -l "$1" ;;
	*.o) nm "$1";;
	*.torrent) transmission-show "$1" ;;
	*.md) glow -s dark "$1" ;;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp) #*.gif
			image "$1" "$2" "$3" "$4" "$5" ;;
	*.svg)
		[ ! -f "${CACHE}.jpg" ] && \
			convert "$1" "${CACHE}.jpg"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5" ;;
	*.pdf)
		[ ! -f "${CACHE}.jpg" ] && \
			pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5" ;;
	*) xdg-mime query filetype "$1" | grep "text/plain" && batorcat "$1" ;;
esac
exit 1

#*.avi|*.mp4|*.mkv) 	;;