# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by generic pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
# 	'{pattern}' = '{icon}'
#
# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beatifull icon
#
# verbose format:
# 
#	'{pattern}' = { type = 'generic' | 'exact', value = '{icon}' }
#
#
# If it couldn't match something it will print:
# 
# WARN [sworkstyle:config] No match for '{app_name}' with title '{title}' 
#
# You can use {title} to do a generic matching 
# You can use {app_name} to do an exact match

# https://www.nerdfonts.com/cheat-sheet

fallback = ''

[matching]
'balena-etcher' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Insomnia' = ''
'Bitwarden' = ''
'/micro/' = ''
'/mc/' = ''
'/Google Chrome/' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Spotify' = ''
'Nextcloud' = ''
'Typora' = ''
'audacious' = ''
'/pulsemixer/' = ''
'file-roller' = ''
'lightcord' = ''
'gnome-calculator' = ''
'GitHub Desktop' = ''
'/(?i)Youtube.*librewolf/' = ''
'/(?i)Github.*librewolf/' = ''
'librewolf' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'Alacritty' = ''
'wdisplays' = '󰹑'
'Evolution' = '󰇰'
'Abiword' = '󰈭'
'libreoffice-writer' = '󰈭'
'libreoffice-calc' = '󰧷'
'org.inkscape.inkscape' = '󱍓'
'blender' = '󰂫'
'code-oss' = '󰨞'
'/Code - OSS/' = '󰨞'
'Code' = '󰨞'
'Code - Insiders' = '󰨞'
'XTerm' = '󰆍'
'kitty' = '󰆍'
'foot' = '󰆍'
'Foot' = '󰆍'
'termite' = '󰆍'
'Navigator' = '󰈹'
'brave-browser' = '󰖟'
'Evince' = '󰈦'
'gimp' = '󰏘'
'gimp-2.10' = '󰏘'
'pamac-manager' = '󱗫'
'telegramdesktop' = '󰔁'
'nautilus' = '󰝰'
'Thunar' = '󰝰'
'pcmanfm' = '󰝰'
'VirtualBox' = '󰽋'
'VirtualBox Manager' = '󰽋'
'Virt-manager' = '󰽋'
'VirtualBox Machine' = '󰻏'
'pantheon-music' = '󱏦'
'font-manager' = '󰬴'
'atom' = '󰝨'
'/GParted/' = ''
'/Gittyup/' = ''
'/STM32CubeMC/' = ''
'/Timeshift/' = '力'
'/KiCad/' = ''
'/Symbol Editor/' = ''
'/Редактор символов/' = ''
'/Footprint Editor/' = ''
'/Редактор посад.мест/' = ''
'/Schematic Editor/' = ''
'/Редактор схем/' = ''
'/PCB Editor/' = ''
'/Редактор печатных плат/' = ''
'/PCB Calculator/' = ''
'/Расчет параметров платы и компонентов/' = ''
